export const defaultTheme = {
  colors: {
    primary: '#1976d2',
    secondary: '#424242',
    background: '#f5f5f5',
    surface: '#ffffff',
    error: '#d32f2f',
    warning: '#ffa000',
    info: '#0288d1',
    success: '#388e3c',
    text: {
      primary: '#212121',
      secondary: '#757575',
      disabled: '#bdbdbd',
    },
  },
  spacing: (factor: number) => `${factor * 8}px`,
  typography: {
    fontFamily: '"Roboto Thin", "Roboto", "Helvetica", "Arial", sans-serif',
    fontSize: 16,
    fontWeightLight: 100,
    fontWeightRegular: 300,
    fontWeightMedium: 400,
    h1: { fontSize: '2.5rem', fontWeight: 100 },
    h2: { fontSize: '2rem', fontWeight: 100 },
    h3: { fontSize: '1.75rem', fontWeight: 100 },
    h4: { fontSize: '1.5rem', fontWeight: 100 },
    h5: { fontSize: '1.25rem', fontWeight: 100 },
  },
};

export const cssNumbers = {
  animation: {
    introDuration: 1.5,
    subtitleDuration: 2,
    bodyHeaderDuration: 3,
    wordStagger: 5,
    charStagger: 0.05,
    scrubDuration: 1,
    sectionScrollSpan: 200,
    hideDuration: 3,
    colorChangeDuration: 0.2,
    titleStartX: 750,
    navStartY: -70,
    scrollEnd: 1000,
    overlapEnd: 1500,
    scrubScale: 10,
    wordStart: 100,
    eases: {
      power1Out: "power1.out",
      power1In: "power1.in",
      power2Out: "power2.out",
    },
  },
  layout: {
    titleFontSize: '200px',
    mediumFontSize: '100px',
    subtitleFontSize: '50px',
    bodyFontSize: '25px',
    textHeaderFontSize: '20px',
    scrubFontSize: '5000px',
    paddingSmall: 10,
    paddingBody: 50,
    fullHeight: '100vh',
    doubleFullHeight: '500vh',
    bodyHeight: '200vh',
    bodySectionOffsetHow: 300,
    bodySectionOffsetWhat: 1000,
    aboutHeight: '100vh',
    textBoxMargin: "500px",
    marginSmallLeft: '20px',
    marginSmallRight: '20px',
    marginSmallTop: '20vh',
    marginSmallBottom: '20px',
    marginExtraSmallLeft: '5vh',
    marginExtraSmallRight: '5vh',
    marginExtraSmallTop: '5vh',
    marginExtraSmallBottom: '5vh',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    // Extra small variant
    marginBottomXs: '20px',
  },
  testing: {
    border: "1px solid red"
  }
};