export const defaultTheme = {
  colors: {
    primary: '#1976d2',
    secondary: '#424242',
    background: '#f5f5f5',
    surface: '#ffffff',
    error: '#d32f2f',
    warning: '#ffa000',
    info: '#0288d1',
    success: '#388e3c',
    text: {
      primary: '#212121',
      secondary: '#757575',
      disabled: '#bdbdbd',
    },
  },
  spacing: (factor: number) => `${factor * 8}px`,
  typography: {
    fontFamily: '"Roboto Thin", "Roboto", "Helvetica", "Arial", sans-serif',
    fontSize: "1rem",
    fontWeightLight: 100,
    fontWeightRegular: 300,
    fontWeightMedium: 400,
    h1: { fontSize: '2.5rem', fontWeight: 100 },
    h2: { fontSize: '2rem', fontWeight: 100 },
    h3: { fontSize: '1.75rem', fontWeight: 100 },
    h4: { fontSize: '1.5rem', fontWeight: 100 },
    h5: { fontSize: '1.25rem', fontWeight: 100 },
  },
};

export const cssNumbers = {
  animation: {
    introDuration: 1.5,
    subtitleDuration: 2,
    bodyHeaderDuration: 3,
    wordStagger: 5,
    charStagger: 0.05,
    scrubDuration: 1,
    sectionScrollSpan: 200,
    hideDuration: 3,
    colorChangeDuration: 0.2,
    titleStartX: "46.875rem",
    navStartY: "-4.375rem",
    scrollEnd: 1000,
    overlapEnd: 1500,
    scrubScale: 10,
    textOffset: {
      xs: 325,
      s: 0,
      m: 375,
      l: 375,
      xl: 375
    },
    wordStart: 100,
    eases: {
      power1Out: "power1.out",
      power1In: "power1.in",
      power2Out: "power2.out",
      none: "none",
      expoOut: "expo.out",
    },
    endMultiplier: 1.3,
    scrub: 1.5,
    scrollRectDuration: 1.2,
    imagesOpacity: 0.7,
    imagesFadeDuration: 0.9,
    imagesFadeOffset: 0.15,
    syncPointOffset: 0.2,
    titleFadeDuration: 0.8,
    biosOverlapBack: 0.1,
    biosDelay: 0.25,
    teamEnterXPercent: 12,
    teamEnterDuration: 1.2,
    teamStaggerEach: 0.22,
    teamStaggerFrom: "center" as const,
    teamStaggerAmount: 0.9,
    bodySectionOffsetHow: 250,
    bodySectionOffsetWhat: 800,
  },
  layout: {
    titleFontSize: { xs: "5rem", s: "8.5rem", m: "10.5rem", l: "12.5rem", xl: "12.5rem" },
    mediumFontSize: "6.25rem",
    subtitleFontSize: "3.125rem",
    footerFontSize: "0.8125rem",
    teamFontSize: "0.9375rem",
    bodyFontSize: "1.5625rem",
    textHeaderFontSize: "1.25rem",
    scrubFontSize: {
      xs: "312.5rem",
      s: "312.5rem",
      m: "312.5rem",
      l: "312.5rem",
      xl: "312.5rem",
    },
    paddingSmall: "0.625rem",
    paddingTransitionText: "5rem",
    paddingBody: "3.125rem",
    paddingTeam: "5.625rem",
    halfHeight: '50dvh',
    threeQuartersHeight: '75dvh',
    fullHeight: '100dvh',
    oneAndHalfHeight: '150dvh',
    oneAndThreeQuartersHeight: '175dvh',
    doubleFullHeight: '200dvh',
    aboutHeight: '130dvh',
    teamHeight: '150dvh',
    teamFullWidth: "100dvw",
    textBoxMargin: "500px",
    marginSmallLeft: '2dvw',
    marginSmallRight: '2dvw',
    marginSmallTop: '20dvh',
    marginSmallBottom: '2dvh',
    marginExtraSmallLeft: '5dvh',
    marginExtraSmallRight: '5dvh',
    marginExtraSmallTop: '5dvh',
    marginExtraSmallBottom: '5dvh',
    paddingLeft: "0.625rem",
    paddingRight: "0.625rem",
    paddingTop: "0.625rem",
    paddingBottom: "0.625rem",
    teamImageMaxWidth: '25dvw',
    aboutFullWidth: '100dvw',
    aboutTitleWidth: '50dvw',
    aboutContentWidth: '41dvw',
    aboutContentPaddingTop: "2dvh",
    aboutContentHeight: '100',
    aboutTitleSpeed: 0.75,
    aboutContentSpeed: 1,
    aboutParallaxDistance: {
      xs: "15dvh",
      s: "15dvh",
      m: "15dvh",
      l: "30dvh",
      xl: "30dvh",
    },
    footerContactTranslateY: '-6dvh',
    footerLinkMargin: '5dvw',
    footerLinkGap: '5dvw',
    footerSocialGap: '2dvw',
    footerSocialIconScale: 1.5,
    marginBottomXXs: '2dvh',
  },
  testing: {
    border: ""
  }
};
