name: CI

on: [push, pull_request, coverage]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # 1. Check out your code
            - uses: actions/checkout@v3

            # 2. Install pnpm CLI
            - uses: pnpm/action-setup@v2
              with:
                  version: 8 # or whatever major you need

            # 3. Install dependencies (in your monorepo, if you need only `frontend`):
            - run: pnpm install --recursive

            # 4. Run your tests
            - run: pnpm --filter frontend exec vitest run --environment jsdom --coverage

            # 5. Run the coverage report
            - run: pnpm --filter frontend run coverage
